version: "3.3"
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      # It would be nice here to support OSes that don't have /tmp
      # See: https://github.com/docker/compose/issues/3344
      - "/tmp/var_lib_postgresql_data:/var/lib/postgresql/data"
  cms_test:
    container_name: cms
    build: .
    depends_on:
      - "db"
    environment:
      CMS_CONFIG: /usr/local/etc/cms-testdb.conf
    volumes:
      - "./codecov:/home/cmsuser/cms/codecov"
    mem_limit: 32g
    memswap_limit: 32g
    ports:
      - 8888:8888
      - 8889:8889
      - 8890:8890
    privileged: true
    
    command: >
      wait-for-it db:5432 -- bash -c '
      createdb --host=db --username=postgres cmsdb ;
      createdb --host=db --username=postgres cmsdbfortesting ;
      cmsInitDB ;
      sudo chown cmsuser:cmsuser ./codecov ;

      sudo chmod 777 /usr/local/lib/python3.8/dist-packages/cms-1.5.dev0-py3.8.egg/cms/grading/Sandbox.py;
      sudo sed -i "s/self.cgroup = config.use_cgroups  # --cg/#self.cgroup = config.use_cgroups  # --cg/g" /usr/local/lib/python3.8/dist-packages/cms-1.5.dev0-py3.8.egg/cms/grading/Sandbox.py; 
      sudo sed -i "s/8e045a51e4b102ea803c06f92841a1fb/`python3 -c "from cmscommon import crypto; print(crypto.get_hex_random_key())"`/g" /usr/local/etc/cms.conf;

      echo -e "name: \"Contest\" \ndescription: \"Contest\" " > contest.yaml;
      sudo cmsImportContest .;
      sudo cmsRankingWebServer & 
      sudo cmsResourceService -a 1;
      '